---
- name: configure timezone
  template:
    src: timezone
    dest: /etc/timezone
    owner: root
    group: root
  notify: reconfigure tzdata

- name: install tzdata
  apt: pkg=tzdata state=present

- name: install ntp
  apt: pkg=ntp state=present

- name: set ntp server
  lineinfile: dest=/etc/ntp.conf state=present line='pool {{ item }} iburst'
  notify: restart ntp
  with_items: "{{ ntp_servers }}"

# Note that there may be more than one 'server' line in this file (hence we
# cannot do this with just one regexp rule).
- name: remove all other ntp servers
  lineinfile: dest=/etc/ntp.conf state=absent regexp="^pool\s+(?!({{ ntp_servers | join('|') }}))"
  notify: restart ntp

- name: start ntp
  service: name=ntp state=started enabled=true
