# Add source repository into sources list.
block:
  - name: Enable backports repo
  apt_repository:
    repo: deb http://deb.debian.org/debian jessie-backports-sloppy main
    state: present
  when: ansible_distribution_major_version == "8"

  - name: Enable backports repo
  apt_repository:
    repo: deb http://deb.debian.org/debian stretch-backports main
    state: present
  when: ansible_distribution_major_version == "9"
when: ansible_os_family == "Debian"

- name: install cockpit
    package: name=cockpit state=present update_cache=yes