---
- name: Provision debian machine for justice DVZ
  hosts: all
  gather_facts: yes
  environment: "{{proxy_env}}"
  roles:
    - base
    - firewall
    - ntp
    - realmd
    - cockpit
    - zabbix
    - backedup
    - docker
