---
- name: Make sure required packages are in place
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - packagekit
    - policykit-1
    - realmd
    - sssd
    - sssd-tools
    - libnss-sss
    - libpam-sss
    - adcli

# - name: Add domin to realm config file
#   lineinfile:
#     path: /etc/realmd.conf
#     insertafter: EOF
#     line: '[{{ domain }}]'
#     create: yes
#     owner: root
#     group: root
#     mode: 0644

# - name: Set the OU where to put the computer
#   lineinfile:
#     path: /etc/realmd.conf
#     state: present
#     insertafter: '[{{ domain }}]'
#     line: 'computer-ou = {{ realmd.server_ou }}'
#     # validate: '/usr/sbin/visudo -cf %s'
#   when: realmd.server_ou is defined

- name: Joins the computer to domain
  command: "realm join {{ domain | quote }} --user '{{ realmd.join_user.name }}' --computer-ou '{{ realmd.server_ou }}'"
  args:
    stdin: '{{ realmd.join_user.password }}'
