---
- name: Make sure required packages are in place
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - packagekit
    - policykit-1
    - realmd
    - sssd
    - sssd-tools
    - libnss-sss
    - libpam-sss
    - adcli

- name: Enable backports repo for jessie
  apt_repository:
    repo: deb http://deb.debian.org/debian jessie-backports main
    state: present
  when: (ansible_os_family == "Debian" and ansible_distribution_major_version == "8")

- name: Install pexpect
  package:
    name: python-pexpect
    state: latest

- include_tasks: realmd.yml
  when: realmd.disabled is not defined
