---
- name: Make sure required packages are in place
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - packagekit
    - policykit-1
    - realmd
    - sssd
    - sssd-tools
    - libnss-sss
    - libpam-sss
    - adcli

- name: Install pexpect
  package:
    name: python-pexpect
    state: latest

- include_tasks: realmd.yml
  when: realmd.disabled is not defined
