# - name: Check if zabbix-agent is installed
#   command: dpkg-query -W zabbix-agent
#   register: zabbix_agent_check
#   failed_when: zabbix_agent_check.rc > 1
#   changed_when: zabbix_agent_check.rc == 1

- name: Install debt packages from justice cloud
  apt:
    deb: "{{ item.url }}"
  with_items: "{{ backup__package_list }}"
