---
- name: install some commonly used packages
  apt: pkg={{ item }} state=present
  with_items:
    - fail2ban
    - git
    - htop
    - tmux
    - vim
    - unattended-upgrades

- name: set the server message of the day explaining ansible was the configuration management tool
  copy: src=motd
        dest=/etc/motd
        mode=644

- name: disable ssh root logins without the use of a valid ssh key
  lineinfile: dest=/etc/ssh/sshd_config state=present regexp='^PermitRootLogin ' line='PermitRootLogin no'
  notify: restart sshd

- name: disable ssh password logins for regular users
  lineinfile: dest=/etc/ssh/sshd_config state=present regexp='^PasswordAuthentication ' line='PasswordAuthentication no'
  notify: restart sshd

- name: enable unattended security updates option
  debconf: name=unattended-upgrades
           question='unattended-upgrades/enable_auto_updates'
           value='true'
           vtype='boolean'
  notify: reconfigure unattended-upgrades
