# import rpm repo
- name: Instalace repozitáře [Zabbix:3.4, Centos 7]
  yum:
    name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
    state: present

- name: Instalace zabbix agenta
  yum:
    name: zabbix-agent
    state: latest
    update_cache: yes
