---
# Instalace a konfigurace zabbix-agent
# Instalace aktuální verze zabbix agenta z oficiálních repozitářu třetí strany,
# doplnění konfiguračního souboru na cílový zabbix server a definice hostname
# sledovaNého serveru (fqdn dle řídícho domenóvého serveru)

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release >= 7

- include_tasks: debian.yml
  when: ansible_os_family == "Debian" and ansible_lsb.major_release >= 8

- name: Enable zabbix-agent service
  service:
    name: zabbix-agent
    enabled: yes

#### modifikace zabbix_agent.conf
- name: Konfigurace zabbix agenta
  block:
    - lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: Server={{ zabbix__server }}
        # validate: ##### Passive checks related
      notify: restart zabbix-agent
    - lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive={{ zabbix__server }}'
        # validate: ##### Active checks related
      notify: restart zabbix-agent
    - lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: Hostname={{ zabbix__hostname_fqdn }}
        # validate: ##### Active checks related
      notify: restart zabbix-agent
    - lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Include='
        state: absent
        # validate: ##### Active checks related
      notify: restart zabbix-agent

# firewall is disabled and for the moment bindings for python2 do not work on debian for offline firewall (cuz old version)
# - name: open port 10050-10051/tcp on firewalld
#   firewalld:
#     port: 10050-10051/tcp
#     state: enabled
#     permanent: true
#   notify: restart firewalld
